spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    url: jdbc:h2:mem:taskmanager
    username: "sa"
    password: "sa"
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        web-allow-others: true

logging:
  level:
    root: info
    web: info

springdoc:
  swagger-ui:
    path: /swagger

server:
  error:
    include-stacktrace: on_param