services:
  client-backend:
    image: test_task-1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/mydatabase

  service-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
